# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
