# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170519_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, null=True),
        ),
    ]
