# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_calendar', '0002_auto_20170505_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
